// docling-project/ScreenParser のモデルカードに記載された55クラスのラベル一覧。
// クラスIDはモデルの出力順（学習時のクラスインデックス）と一致させる必要がある。
// 実際にエクスポートしたモデルの `model.names` と突き合わせて確認すること。
export const CLASS_NAMES = [
  'Table',
  'Column/Browser',
  'Button',
  'Utility Button',
  'App Icon',
  'Navigation Bar',
  'Status Bar',
  'Search Field',
  'Toolbar',
  'Tooltip',
  'Video',
  'Tab Bar',
  'Side Bar',
  'Slider',
  'Picker',
  'ContextMenu',
  'DockMenu',
  'EditMenu',
  'Image',
  'Scroll',
  'Switch',
  'File Icon',
  'Chart',
  'Window',
  'Screen',
  'List',
  'List Item',
  'PopUp Menu',
  'Steppers',
  'Toggles',
  'Text Input',
  'Rating Indicator',
  'Checkbox',
  'Radiobox',
  'Select',
  'Avatar',
  'Badge',
  'Alert',
  'Progress bar',
  'Bottom navigation',
  'Breadcrumb',
  'Page control',
  'Link',
  'Menu',
  'Pagination',
  'Tab',
  'Search Bar',
  'Date-Time picker',
  'Calendar',
  'Text',
  'Heading',
  'Code snippet',
  'Carousel',
  'Notification',
  'Logo',
] as const

export type ClassName = (typeof CLASS_NAMES)[number]
